name: image_reco
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ✅ Required dependencies based on your imports
  image: ^4.1.7
  tflite_flutter: ^0.11.0
  path_provider: ^2.1.2
  image_picker: ^1.1.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/model/quickdraw_cnn.tflite
    - lib/assets/model/categories.txt
